# Generated by Django 4.2 on 2025-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorvariant",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="sizevariant",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
